// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuzehtilnbjtkrvghhef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51emVodGlsbmJqdGtydmdoaGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzYwMjQsImV4cCI6MjA1OTU1MjAyNH0.k8OZZmIYfiVVAYdQD4jVIzJoDrKaSnYqCnN63T3QqV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);